# Generated by Django 5.1.1 on 2024-09-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_passage_question_passage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
