# Generated by Django 5.1.1 on 2024-09-27 05:18

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_passage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='Core.category'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='text',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
